tenant: tyvdh
app: stellarauth
service: stellarauth

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-domain-manager

custom:
  customDomain:
    domainName: ${opt:subdomain}.stellarauth.com
    certificateName: ${opt:subdomain}.stellarauth.com
    stage: ${opt:stage}
    createRoute53Record: false
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  serverless-offline:
    httpsProtocol: certs
    port: 4000

provider:
  name: aws
  runtime: nodejs10.x
  stage: ${opt:stage}
  region: us-east-1
  environment: ${file(env.yml):${opt:stage}}

functions:
  auth:
    handler: handler.auth
    events:
      - http:
          path: auth
          method: get
          cors: true

  createApp:
    handler: handler.app
    events:
      - http:
          path: app
          method: POST
          cors: true

  createUser:
    handler: handler.user
    events:
      - http:
          path: user
          method: POST
          cors: true
  
  keyCreate:
    handler: handler.key
    events:
      - http:
          path: key/create
          method: POST
          cors: true
  keyClaim:
    handler: handler.key
    events:
      - http:
          path: key/claim
          method: POST
          cors: true
  keyVerify:
    handler: handler.key
    events:
      - http:
          path: key/verify
          method: POST
          cors: true
  keyValidate:
    handler: handler.key
    events:
      - http:
          path: key/validate
          method: POST
          cors: true

  txnSend:
    handler: handler.txn
    events:
      - http:
          path: txn/send
          method: POST
          cors: true
  txnSign:
    handler: handler.txn
    events:
      - http:
          path: txn/sign
          method: POST
          cors: true
  txnList:
    handler: handler.txn
    events:
      - http:
          path: txn
          method: GET
          cors: true